name: Check Patch

on: [pull_request]

jobs:
  checkpatch:
    runs-on: ubuntu-latest
    name: Check Patch for Pull Request
    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
    - name: Checkpatch
      uses: tedd-an/action-checkpatch@master
      with:
        github_token: ${{ secrets.ACTION_TOKEN }}
