name: Check Patch

on: [pull_request]

jobs:
  check_patch:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: check env
      run: |
        echo "Environment"
        env
        echo "End of Env"
