name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI for Pull Request
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2
      with:
        path: src

    - name: CI
      uses: tedd-an/action-ci@dev
      with:
        src_path: src
        github_token: ${{ secrets.ACTION_TOKEN }}
        email_token: ${{ secrets.EMAIL_TOKEN }}
