name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI for Pull Request
    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
    - name: CI
      uses: tedd-an/action-ci@dev
      with:
        github_token: ${{ secrets.ACTION_TOKEN }}
        email_token: ${{ secrets.EMAIL_TOKEN }}
