name: Code Scan

on:
  schedule:
  - cron:  "* */6 * * *"

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: src
    - name: Coverity Scan
      uses: tedd-an/action-code-scan@dev
      with:
        src_path: src
        scan_tool: "coverity"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        email_token: ${{ secrets.EMAIL_TOKEN }}

  clang-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: src2
    - name: Clang Code Scan
      uses: tedd-an/action-code-scan@dev
      with:
        src_path: src2
        scan_tool: "clang"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        email_token: ${{ secrets.EMAIL_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:
        name: scan_report
        path: scan_report.tar.gz

